### ISSUE TITLE
Default sat level

### ISSUE THREAD

**Issue by iancrossfield** [natashabatalha/PandExo#1]
In exo_input.json, the default saturation level is listed as " `in % sat level' ", which throws an exception whenever saturation level has not been defined.  instead, the default should be some reasonable value (10%, 50%, 80%) so that the code runs.

**Comment by iancrossfield** [comment]
And perhaps: saturation level should be an integer between 0 and 1, rather than a percentage.

**Comment by natashabatalha** [comment]
As soon as official Webb recommendations come through for this number, they will be put in as defaults. Until then, I want to make sure people have full control over this parameter since 10% and 80% can yield wildly different results.
