### ISSUE TITLE
wbin: error when binning 

### ISSUE THREAD

**Issue by iancrossfield** [natashabatalha/PandExo#18]
In jwst.py, the line "wbin = wbin[photon_out_bin > 0 ]" throws the error "TypeError: only integer scalar arrays can be converted to a scalar index" because bin_wave_to_R returns a list (not a NumPy array). Either that functions output should always be cast to type array on return, or the offending line above should be changed to: "wbin = np.array(wbin)[photon_out_bin > 0 ]"

Thanks for making these great tools publicly available.

**Comment by natashabatalha** [comment]
Fixed w/ `return np.array(wave)`. Thanks for point it out. I hardly ever use that R function so it would've gone unnoticed!
