### ISSUE TITLE
Clarify pandeia data version in `pandexo.sh`?

### ISSUE THREAD

**Issue by zkbt** [natashabatalha/PandExo#19]
The `pandexo.sh` looks to be expecting a file called `pandeia_data-1.1.1.tar` for the pandeia data. However, the most recent pandeia data for download, as linked to on the [docs](https://natashabatalha.github.io/PandExo/installation.html#jwst-reference-data) has a newer version (`pandeia_data-1.2.tar`). Perhaps you could update the install script, and also ensure that 1.2 is the version we should be using? Thanks!

**Comment by natashabatalha** [comment]
Done! Notice the file now untars as pandeia_data (sans version number). Also added in a bonus sphinx=1.5.6 requirement that I think is breaking people's updates
