### ISSUE TITLE
Handling missing values when loading system parameters from exo.MAST

### ISSUE THREAD

**Issue by kevin218** [natashabatalha/PandExo#30]
We already discussed this issue, but I'm putting in writing...

PandExo breaks when retrieving parameters for some planetary systems.  This happens because some exo.MAST fields are empty.

A reasonable solution might be to have a "Resolve Target" button that, when clicked, retrieves the system parameters from exo.MAST, reloads the page, and populates fields for which there is information.  I don't know how to implement this, but we do something similar in ExoCTK.

**Comment by natashabatalha** [comment]
Fixed by @mfixstsci  with https://github.com/natashabatalha/PandExo/pull/37
