### ISSUE TITLE
Incompatibility with pandeia.engine version 1.5.1

### ISSUE THREAD

**Issue by r-cloutier** [natashabatalha/PandExo#32]
The current version of pandeia reference data (v 1.5.1) is incompatible with the current version of PandExo. The PandExo installation page redirects the user to https://pypi.org/project/pandeia.engine, wherein the dependent package pandeia.engine is said to be installed via 

$ pip install pandeia.engine

This results in an incompatibility with PandExo and a failure of its test script "run_test.py". Myself, along with another independent tester, have confirmed that this can be mitigated by 1) installing PandExo as per its installation instructions and 2) installing a specific (older) version of pandeia via

$ pip install pandeia.engine==1.4.0

We hope that this will save future users some of our heartache.

**Comment by natashabatalha** [comment]
Sorry you had to deal with this! Thanks for posting with an informative title. See this issue comment. Feel free to grab the dev branch that has 1.5.1. https://github.com/natashabatalha/PandExo/issues/31#issuecomment-586430937
