### ISSUE TITLE
spectral sampling

### ISSUE THREAD

**Issue by pcubillos** [natashabatalha/PandExo#36]
Hi,
I was looking at the example at https://natashabatalha.github.io/PandExo/tutorialjwst.html and noted that when I print out:
```python
# ...
R_in = 100.0
x, y, e = jpi.jwst_1d_spec(out, R=R_in, num_tran=10, model=False, x_range=[0.8, 1.28])

wl = x[0]
R_out = wl[1:]/np.ediff1d(wl)
print(R_out)
```
I get numbers close to R_out ~ 2*R_in.  Is this intended?, I would have expected to get R_out~R_in.  In any case, I think it might be a good idea to document what the code means by R.

**Comment by natashabatalha** [comment]
Good question. I adopt R as w[1]/(w[2] - w[0]) to maintain consistency with `pandeia.engine`. I will add this to documentation

**Comment by natashabatalha** [comment]
Added to `bintools` docs: 

https://github.com/natashabatalha/PandExo/blob/b9f1f0630491234f82cc883b8de639239dc4df72/pandexo/engine/bintools.py#L29

And to `jwst_1d_spec`

https://github.com/natashabatalha/PandExo/blob/b9f1f0630491234f82cc883b8de639239dc4df72/pandexo/engine/justplotit.py#L33
