### ISSUE TITLE
`jdi.run_pandexo` not reading input instrument dictionary

### ISSUE THREAD

**Issue by jaymedina** [natashabatalha/PandExo#38]
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/32107699/76336473-7096c180-62cc-11ea-95b9-62238f51e263.png">
I'm trying to generate a MIRI LRS trace after just 1 exposure, but it seems like it's running the default parameters, not the instrument dictionary `inst_dict` I'm feeding it. 

I proved this by comparing my results when running the default setting of 10 exposures, and compared the 2 arrays. In this cell I took a `np.mean()` of both arrays for quick comparison. 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/32107699/76336776-dbe09380-62cc-11ea-9e0e-b730f4ac43cf.png">

**Comment by natashabatalha** [comment]
`PandeiaOutTrans['2d']['detector']` is a rate in e/s. Therefore if you are inputting the same star, then you would expect that rate to not change. The trace in these simulations (for MIRI LRS) is assumed to be constant across the detector. You won't see any curvature, as with the NIRISS SOSS simulations.  Is that what you are after?

**Comment by jaymedina** [comment]
@natashabatalha Hi Natasha, yes, I've generated traces for MIRI LRS for ExoCTK's contamination calculator, but we're getting weird results for MIRI, and we are predicting that it's because the default `nexp` is set to 10 exposures. For MIRI LRS there cannot be more than 1 exposure. Since each exposure takes a certain # of seconds to complete, wouldn't the number of exposures affect the the amount of electrons you are getting per second, and thus affecting the mean value in `PandeiaOutTrans['2d']['detector']`?

**Comment by jaymedina** [comment]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/32107699/76343878-1b13e200-62d7-11ea-82e9-c357f10ffa62.png">

The plot above is from JWST ETC: I'm getting a little over 0.8 electrons per second for MIRI LRS, but the values in the output pandexo array are in the 10,000s? Are the units different?

![image](https://user-images.githubusercontent.com/32107699/76343761-f4ee4200-62d6-11ea-9889-6270fb94c010.png)

Why is the pixel value

**Comment by natashabatalha** [comment]
That `nexp` is just a place holder. It gets set to 1 in the code: 

https://github.com/natashabatalha/PandExo/blob/ce3100fad9609509286bbcf3155be247ebc7ea97/pandexo/engine/jwst.py#L339

Can you send the stellar info? jmag, teff, logg, and feh. The detector 2d image is a bit different than what you are looking at in the ETC. I think what you are looking for from Pandeia is this : 

https://github.com/natashabatalha/PandExo/blob/ce3100fad9609509286bbcf3155be247ebc7ea97/pandexo/engine/jwst.py#L344-L346

**Comment by jaymedina** [comment]
```
exo_dict['star']['mag'] = 8.0               #magnitude of the system
exo_dict['star']['ref_wave'] = 1.25         #For J mag = 1.25, H = 1.6, K =2.22.. etc (all in micron)
exo_dict['star']['temp'] = 4500             #in K
exo_dict['star']['metal'] = 0.0             # as log Fe/H
exo_dict['star']['logg'] = 4.0
```
@natashabatalha

**Comment by jaymedina** [comment]
@natashabatalha since `nexp` is a place holder, how do I know what parameters in my instrument dictionary `inst_dict` are being read and applied by `justdoit`?

**Comment by natashabatalha** [comment]
@jaymedina I lost track of what the issue was here. Is there something that still needs fixing here?
