### ISSUE TITLE
Setting path for Fortney Grid File 

### ISSUE THREAD

**Issue by wj198414** [natashabatalha/PandExo#42]
I tried to run JWST_Running_Pandexo.ipynb and had the following issue:

Exception: Fortney Grid File Path is incorrect, or not initialized

How do I set that up?

Thanks,
Ji

**Comment by natashabatalha** [comment]
The data is located within this link: 

https://exoctk.stsci.edu/zip_data_download

**Comment by wj198414** [comment]
I kept getting errors downloading the data. Can you please try and let me know if you have the same problem?

(pandexo) dapangs-MacBook-Air:Downloads dapang182$ wget https://exoctk.stsci.edu/zip_data_download
--2020-03-13 10:13:13--  https://exoctk.stsci.edu/zip_data_download
Resolving exoctk.stsci.edu... 130.167.165.40
Connecting to exoctk.stsci.edu|130.167.165.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14559714620 (14G) [application/zip]
Saving to: 'zip_data_download'

zip_data_download    11%[=>                    ]   1.57G  6.91MB/s   in 4m 2s  s

2020-03-13 10:17:16 (6.65 MB/s) - Connection closed at byte 1690526557. Retrying.

--2020-03-13 10:17:17--  (try: 2)  https://exoctk.stsci.edu/zip_data_download
Connecting to exoctk.stsci.edu|130.167.165.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14559714620 (14G) [application/zip]
Saving to: 'zip_data_download'

zip_data_download    11%[=>                    ]   1.55G  7.26MB/s   in 4m 3s  s

2020-03-13 10:21:20 (6.54 MB/s) - Connection closed at byte 1690526557. Retrying.

--2020-03-13 10:21:22--  (try: 3)  https://exoctk.stsci.edu/zip_data_download
Connecting to exoctk.stsci.edu|130.167.165.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14559714620 (14G) [application/zip]
Saving to: 'zip_data_download'

zip_data_download    11%[=>                    ]   1.51G  7.04MB/s   in 4m 3s  s

2020-03-13 10:25:25 (6.38 MB/s) - Connection closed at byte 1690526557. Retrying.

--2020-03-13 10:25:28--  (try: 4)  https://exoctk.stsci.edu/zip_data_download
Connecting to exoctk.stsci.edu|130.167.165.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14559714620 (14G) [application/zip]
Saving to: 'zip_data_download'

**Comment by natashabatalha** [comment]
Can you just click on the link and download the file? I am not having any issues with that.

**Comment by wj198414** [comment]
I tried both clicking the link and wget, both failed. I have a second person try and it failed. The download seems to stop at ~1.5 G mark.

**Comment by wj198414** [comment]
We have been trying for the past few days but without success. Is there an alternative way of getting the data? Many thanks!

**Comment by natashabatalha** [comment]
Here is a temporary link: 

https://drive.google.com/open?id=11o0-7iCEsA8KhrxZIJWAEr9ugPUwcfk5

Will alert ST that their link is down.

**Comment by wj198414** [comment]
It works! Thanks. Stay healthy!

Ji

Natasha Batalha <notifications@github.com> 于2020年3月17日周二 下午7:01写道：
