### ISSUE TITLE
Cannot import name 'blackbody'

### ISSUE THREAD

**Issue by iancrossfield** [natashabatalha/PandExo#66]
When calling `result = jdi.run_pandexo...`, the following error is thrown:

> /home/exolab/anaconda3/lib/python3.9/site-packages/pandexo.engine-1.5.3.1-py3.9.egg/pandexo/engine/create_input.py in module
>       6 import astropy.constants as c
>       7 import os
> ----> 8 from  astropy.modeling import blackbody as bb
>       9 import warnings
>      10 with warnings.catch_warnings():
> 
> ImportError: cannot import name 'blackbody' from 'astropy.modeling' (/home/exolab/anaconda3/lib/python3.9/site-packages/astropy/modeling/__init__.py)
> 

This seems to be because astropy deprecated their old 'blackbody' module: 
https://docs.astropy.org/en/stable/changelog.html?highlight=blackbody_nu#id288

**Comment by natashabatalha** [comment]
Hi all! Thanks for submitting this and sorry for the long delay. PandExo 2.0 is staged in dev and nearly ready for release. Look out for it soon.
