### ISSUE TITLE
"ValueError: min() arg is an empty sequence" in create_input.py

### ISSUE THREAD

**Issue by yrotman1** [natashabatalha/PandExo#68]
When running `result = jdi.run_pandexo()` I will get an error about once every thousand individual runs:

```wavemin = max([min(wave_planet), min(wave_star), 0.5]) ValueError: min() arg is an empty sequence``` from the ```/pandexo/engine/create_input.py``` file. This doesn't seem to repeat on the same inputted data set and parameters but will rather pop up at random increments for any random data set and parameter input within the loop. I'm not sure if this is something anyone else has run into but I can't seem to diagnose the issue since it seems to be randomly occurring.

**Comment by natashabatalha** [comment]
Very odd! If you find the pattern please let me know. I will leave this open in case others notice the same behavior.

**Comment by natashabatalha** [comment]
Closing after no further reports of this issue
