### ISSUE TITLE
KeyError 'sed_families' in run_test.py

### ISSUE THREAD

**Issue by LTeinturier** [natashabatalha/PandExo#70]
When running the `run_test.py`, I get an error in the `pandeia/engine/sed.py` : 

`  File "/mypathtozecode/python3.7/site-packages/pandeia/engine/sed.py", line 88, in _get_config
    del config[k]
KeyError: 'sed_families'`

I've downloaded the code through pip, did the pip --upgrade for both pandeia and pandexo and i have astropy 4.2.1, to avoid the issue #66 

Any clue what's going on ? 
Thanks

**Comment by natashabatalha** [comment]
Hello! This error is a product of using reference data and software release that are incompatible. 

However, we are currently migrating to PandExo and Pandeia 2.0. If possible, I would recommend using the online interface https://exoctk.stsci.edu/ until we release. 

If you feel so inclined you are free to checkout the `dev` branch and follow the new [installation](https://github.com/natashabatalha/PandExo/blob/dev/docs/installation.rst) guide to install pandeia and pandexo 2.0. However, beware as we are still ensuring the install process is a smooth one!
