### ISSUE TITLE
Incorporate NIRISS Order 2 in PandExo online

### ISSUE THREAD

**Issue by nespinoza** [natashabatalha/PandExo#82]
Hi @natashabatalha,

 Either of us can take this on, but wanted to leave it here for future reference. Currently, PandExo online can't do NIRISS/SOSS Order 2 simulations --- but of course on a locally-installed version one can via `instrument_dictionary['strategy']['order'] = 2`. Need to implement this option in the online version, too.

 I'm a bit thorn as to what the best strategy would be:

- **Easiest would be to add an extra option below "Instrument" whenever NIRISS is selected, on which one could select the Order**. This is the most straightforward because it would be a simple "if" statement in the online codebase. This "dynamic menus" after selecting an instrument is already incorporated in the code.
- **More complex would be to add results of both orders in the final results**. This would be more complicated because it would imply running two simulations, but also because on the final results page it would imply creating some extra space for the two orders.

 Leaving it here for implementation for the next Cycle; cc: @mfixstsci.

N.

**Comment by natashabatalha** [comment]
Has been added to dev, and tested. All good.
